from pptx import Presentation
from pptx.util import Inches, Pt
import os
import re

def create_presentation(md_path, pptx_path, image_map=None):
    prs = Presentation()
    
    # Read Markdown
    with open(md_path, 'r', encoding='utf-8') as f:
        lines = f.readlines()
        
    current_slide = None
    tf = None
    
    for line in lines:
        line = line.strip()
        if not line: continue
        
        # New Slide Detection
        if line.startswith('## '):
            title_text = line.replace('## ', '').strip()
            
            # Determine Layout
            if "Title Slide" in title_text or "Slide 1:" in title_text:
                layout = prs.slide_layouts[0] # Title Slide
            else:
                layout = prs.slide_layouts[1] # Title and Content
                
            current_slide = prs.slides.add_slide(layout)
            
            # Set Title
            title = current_slide.shapes.title
            clean_title = re.sub(r'Slide \d+: ', '', title_text)
            title.text = clean_title
            
            # Body Reset
            if layout == prs.slide_layouts[1]:
                body_shape = current_slide.shapes.placeholders[1]
                tf = body_shape.text_frame
                tf.text = "" 
                
            # IMAGE INSERTION LOGIC
            # If we have a mapped image for this slide index (simplified check by title keywords)
            if image_map:
                img_path = None
                if "Title Slide" in title_text:
                    img_path = image_map.get("logo")
                    if img_path and os.path.exists(img_path):
                        # Add Logo top right
                        current_slide.shapes.add_picture(img_path, Inches(7.5), Inches(0.5), height=Inches(1.0))
                        
                elif "Architecture" in title_text or "Solution" in title_text:
                    img_path = image_map.get("architecture")
                    if img_path and os.path.exists(img_path):
                        # Add Arch Diagram
                        current_slide.shapes.add_picture(img_path, Inches(5), Inches(2), height=Inches(3.5))

                elif "Live Monitoring" in title_text or "Real-Time" in title_text:
                    img_path = image_map.get("dashboard")
                    if img_path and os.path.exists(img_path):
                         current_slide.shapes.add_picture(img_path, Inches(5), Inches(2), width=Inches(4.5))

                elif "Security" in title_text:
                    img_path = image_map.get("data_flow")
                    if img_path and os.path.exists(img_path):
                         current_slide.shapes.add_picture(img_path, Inches(5), Inches(2), width=Inches(4.5))
        
        # Content Parsing
        elif current_slide:
            if prs.slide_layouts.index(current_slide.slide_layout) == 0:
                if line.startswith('* **Main Title**:'):
                    current_slide.shapes.title.text = line.split(':', 1)[1].strip()
                elif line.startswith('* **Subtitle**:'):
                    current_slide.placeholders[1].text = line.split(':', 1)[1].strip()
            else:
                if line.startswith('*') or line.startswith('-'):
                    text = line.lstrip('*- ').strip().replace('**', '')
                    if tf:
                        p = tf.add_paragraph()
                        p.text = text
                        p.level = 0
                elif line.startswith('    *') or line.startswith('    -'):
                    text = line.strip().lstrip('*- ').strip().replace('**', '')
                    if tf:
                        p = tf.add_paragraph()
                        p.text = text
                        p.level = 1

    prs.save(pptx_path)
    print(f"Generated: {pptx_path}")

# Configuration
base_dir = "/root/.gemini/antigravity/brain/80f562b8-1dc5-4c67-85bb-89353b4f5b8e"
md_source = os.path.join(base_dir, "Demo_Presentation.md")
pptx_dest = os.path.join(base_dir, "Monitorix_Demo_Graphic.pptx")

# Map images (Using filenames generated by previous tool calls)
# Note: In real scenarios, these filenames have timestamps. I will listdir to find them.
image_map = {}
for f in os.listdir(base_dir):
    if "monitorix_logo_asset" in f: image_map["logo"] = os.path.join(base_dir, f)
    if "monitorix_architecture" in f: image_map["architecture"] = os.path.join(base_dir, f)
    if "monitorix_dashboard" in f: image_map["dashboard"] = os.path.join(base_dir, f)
    if "monitorix_data_flow" in f: image_map["data_flow"] = os.path.join(base_dir, f)

if os.path.exists(md_source):
    create_presentation(md_source, pptx_dest, image_map)
else:
    print(f"Source not found: {md_source}")
from pptx.util import Inches, Pt
import os
import re

def create_presentation(md_path, pptx_path):
    prs = Presentation()
    
    # Read Markdown
    with open(md_path, 'r', encoding='utf-8') as f:
        lines = f.readlines()
        
    current_slide = None
    body_shape = None
    tf = None
    
    # Simple State Machine
    # Slide layouts: 0=Title, 1=Title+Content
    
    for line in lines:
        line = line.strip()
        if not line: continue
        
        # New Slide Detection (## Header)
        if line.startswith('## '):
            title_text = line.replace('## ', '').strip()
            
            # Decide Layout
            if "Title Slide" in title_text or "Slide 1:" in title_text:
                layout = prs.slide_layouts[0] # Title Slide
            else:
                layout = prs.slide_layouts[1] # Title and Content
                
            current_slide = prs.slides.add_slide(layout)
            
            # Set Title
            title = current_slide.shapes.title
            # Cleaner Title (Remove "Slide X:")
            clean_title = re.sub(r'Slide \d+: ', '', title_text)
            title.text = clean_title
            
            # Prepare Body info
            if layout == prs.slide_layouts[1]:
                body_shape = current_slide.shapes.placeholders[1]
                tf = body_shape.text_frame
                tf.text = "" # Clear default
        
        # Content Parsing
        elif current_slide:
            # Title Slide Logic
            if prs.slide_layouts.index(current_slide.slide_layout) == 0:
                if line.startswith('* **Main Title**:'):
                    current_slide.shapes.title.text = line.split(':', 1)[1].strip()
                elif line.startswith('* **Subtitle**:'):
                    current_slide.placeholders[1].text = line.split(':', 1)[1].strip()
            
            # Content Slide Logic
            else:
                if line.startswith('*') or line.startswith('-'):
                    # Bullet Point
                    text = line.lstrip('*- ').strip()
                    # Bold handling (simple)
                    text = text.replace('**', '')
                    
                    if tf:
                        p = tf.add_paragraph()
                        p.text = text
                        p.level = 0
                elif line.startswith('    *') or line.startswith('    -'):
                    # Nested Bullet
                    text = line.strip().lstrip('*- ').strip()
                    text = text.replace('**', '')
                    if tf:
                        p = tf.add_paragraph()
                        p.text = text
                        p.level = 1

    prs.save(pptx_path)
    print(f"Generated: {pptx_path}")

# Run
md_source = "/root/.gemini/antigravity/brain/80f562b8-1dc5-4c67-85bb-89353b4f5b8e/Demo_Presentation.md"
pptx_dest = "/root/.gemini/antigravity/brain/80f562b8-1dc5-4c67-85bb-89353b4f5b8e/Monitorix_Demo.pptx"

if os.path.exists(md_source):
    create_presentation(md_source, pptx_dest)
else:
    print(f"Source not found: {md_source}")
