"""add_admin_email_final

Revision ID: 32e2a3ab411b
Revises: d40e57ef27bb
Create Date: 2026-02-09 12:09:38.799027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32e2a3ab411b'
down_revision: Union[str, Sequence[str], None] = 'd40e57ef27bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Tenants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('AdminEmail', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Tenants', schema=None) as batch_op:
        batch_op.drop_column('AdminEmail')

    # ### end Alembic commands ###
