"""Add_Event_Activity_Logs

Revision ID: 5658994f9b73
Revises: ad63a9c9b25b
Create Date: 2026-01-02 17:28:40.023302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5658994f9b73'
down_revision: Union[str, Sequence[str], None] = 'ad63a9c9b25b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ActivityLogs',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('AgentId', sa.String(length=50), nullable=True),
    sa.Column('TenantId', sa.Integer(), nullable=True),
    sa.Column('ActivityType', sa.String(length=50), nullable=True),
    sa.Column('ProcessName', sa.String(length=255), nullable=True),
    sa.Column('WindowTitle', sa.Text(), nullable=True),
    sa.Column('Url', sa.Text(), nullable=True),
    sa.Column('DurationSeconds', sa.Float(), nullable=True),
    sa.Column('RiskScore', sa.Float(), nullable=True),
    sa.Column('RiskLevel', sa.String(length=50), nullable=True),
    sa.Column('Timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    with op.batch_alter_table('ActivityLogs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ActivityLogs_AgentId'), ['AgentId'], unique=False)
        batch_op.create_index(batch_op.f('ix_ActivityLogs_Id'), ['Id'], unique=False)

    op.create_table('EventLogs',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('AgentId', sa.String(length=50), nullable=True),
    sa.Column('Type', sa.String(length=50), nullable=True),
    sa.Column('Details', sa.Text(), nullable=True),
    sa.Column('Timestamp', sa.DateTime(), nullable=True),
    sa.Column('RawData', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    with op.batch_alter_table('EventLogs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_EventLogs_AgentId'), ['AgentId'], unique=False)
        batch_op.create_index(batch_op.f('ix_EventLogs_Id'), ['Id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('EventLogs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_EventLogs_Id'))
        batch_op.drop_index(batch_op.f('ix_EventLogs_AgentId'))

    op.drop_table('EventLogs')
    with op.batch_alter_table('ActivityLogs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ActivityLogs_Id'))
        batch_op.drop_index(batch_op.f('ix_ActivityLogs_AgentId'))

    op.drop_table('ActivityLogs')
    # ### end Alembic commands ###
