"""Add_SpeechLogs

Revision ID: 5b0c46e99bd7
Revises: 5658994f9b73
Create Date: 2026-01-02 18:06:25.190503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b0c46e99bd7'
down_revision: Union[str, Sequence[str], None] = '5658994f9b73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('SpeechLogs',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('AgentId', sa.String(length=50), nullable=True),
    sa.Column('AudioUrl', sa.String(length=255), nullable=True),
    sa.Column('TranscribedText', sa.Text(), nullable=True),
    sa.Column('Confidence', sa.Float(), nullable=True),
    sa.Column('DurationSeconds', sa.Float(), nullable=True),
    sa.Column('FlaggedKeywordsJson', sa.Text(), nullable=True),
    sa.Column('Timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    with op.batch_alter_table('SpeechLogs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_SpeechLogs_AgentId'), ['AgentId'], unique=False)
        batch_op.create_index(batch_op.f('ix_SpeechLogs_Id'), ['Id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('SpeechLogs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_SpeechLogs_Id'))
        batch_op.drop_index(batch_op.f('ix_SpeechLogs_AgentId'))

    op.drop_table('SpeechLogs')
    # ### end Alembic commands ###
