"""add_bandwidth_policy_and_missing_fields

Revision ID: 643a3303126c
Revises: 32e2a3ab411b
Create Date: 2026-02-16 11:08:57.561931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '643a3303126c'
down_revision: Union[str, Sequence[str], None] = '32e2a3ab411b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Policies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('RemediationJson', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('BandwidthJson', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Policies', schema=None) as batch_op:
        batch_op.drop_column('BandwidthJson')
        batch_op.drop_column('RemediationJson')

    with op.batch_alter_table('FeatureTrials', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('FeatureTrials_ibfk_1', 'Tenants', ['TenantId'], ['Id'], ondelete='CASCADE')
        batch_op.drop_index(batch_op.f('ix_FeatureTrials_TenantId'))
        batch_op.drop_index(batch_op.f('ix_FeatureTrials_IsActive'))
        batch_op.drop_index(batch_op.f('ix_FeatureTrials_Id'))
        batch_op.create_index('unique_tenant_feature', ['TenantId', 'FeatureName'], unique=True)
        batch_op.create_index('idx_tenant_id', ['TenantId'], unique=False)
        batch_op.create_index('idx_is_active', ['IsActive'], unique=False)

    with op.batch_alter_table('Agents', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('PolicyId')

    # ### end Alembic commands ###
