"""add_public_ips

Revision ID: 67ae673c1df9
Revises: f1a2b3c4d5e6
Create Date: 2026-01-05 20:55:04.363883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67ae673c1df9'
down_revision: Union[str, Sequence[str], None] = 'f1a2b3c4d5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Agents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('PublicIp', sa.String(length=50), nullable=True))

    with op.batch_alter_table('Tenants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('RegistrationIp', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Tenants', schema=None) as batch_op:
        batch_op.drop_column('RegistrationIp')

    with op.batch_alter_table('Agents', schema=None) as batch_op:
        batch_op.drop_column('PublicIp')

    # ### end Alembic commands ###
