"""Add_HashBanks_Fingerprints

Revision ID: 6e5c925a0257
Revises: 5b0c46e99bd7
Create Date: 2026-01-02 18:23:09.293086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e5c925a0257'
down_revision: Union[str, Sequence[str], None] = '5b0c46e99bd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('DigitalFingerprints',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('AgentId', sa.String(length=50), nullable=True),
    sa.Column('HardwareId', sa.String(length=255), nullable=True),
    sa.Column('OS', sa.String(length=100), nullable=True),
    sa.Column('PropertiesJson', sa.Text(), nullable=True),
    sa.Column('Status', sa.String(length=50), nullable=True),
    sa.Column('FirstSeen', sa.DateTime(), nullable=True),
    sa.Column('LastSeen', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    with op.batch_alter_table('DigitalFingerprints', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_DigitalFingerprints_AgentId'), ['AgentId'], unique=False)
        batch_op.create_index(batch_op.f('ix_DigitalFingerprints_HardwareId'), ['HardwareId'], unique=False)
        batch_op.create_index(batch_op.f('ix_DigitalFingerprints_Id'), ['Id'], unique=False)

    op.create_table('HashBanks',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Hash', sa.String(length=255), nullable=True),
    sa.Column('Type', sa.String(length=50), nullable=True),
    sa.Column('Reputation', sa.String(length=50), nullable=True),
    sa.Column('Description', sa.String(length=255), nullable=True),
    sa.Column('Source', sa.String(length=100), nullable=True),
    sa.Column('AddedBy', sa.String(length=100), nullable=True),
    sa.Column('CreatedAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    with op.batch_alter_table('HashBanks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_HashBanks_Hash'), ['Hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_HashBanks_Id'), ['Id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('HashBanks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_HashBanks_Id'))
        batch_op.drop_index(batch_op.f('ix_HashBanks_Hash'))

    op.drop_table('HashBanks')
    with op.batch_alter_table('DigitalFingerprints', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_DigitalFingerprints_Id'))
        batch_op.drop_index(batch_op.f('ix_DigitalFingerprints_HardwareId'))
        batch_op.drop_index(batch_op.f('ix_DigitalFingerprints_AgentId'))

    op.drop_table('DigitalFingerprints')
    # ### end Alembic commands ###
