"""reset_v3

Revision ID: a17b35cf24ee
Revises: 
Create Date: 2026-01-13 10:35:10.058753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a17b35cf24ee'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ActivityLogs',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('AgentId', sa.String(length=50), nullable=True),
    sa.Column('TenantId', sa.Integer(), nullable=True),
    sa.Column('ActivityType', sa.String(length=50), nullable=True),
    sa.Column('ProcessName', sa.String(length=255), nullable=True),
    sa.Column('WindowTitle', sa.Text(), nullable=True),
    sa.Column('Url', sa.Text(), nullable=True),
    sa.Column('DurationSeconds', sa.Float(), nullable=True),
    sa.Column('IdleSeconds', sa.Float(), nullable=True),
    sa.Column('Category', sa.String(length=50), nullable=True),
    sa.Column('ProductivityScore', sa.Float(), nullable=True),
    sa.Column('RiskScore', sa.Float(), nullable=True),
    sa.Column('RiskLevel', sa.String(length=50), nullable=True),
    sa.Column('Timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    with op.batch_alter_table('ActivityLogs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ActivityLogs_AgentId'), ['AgentId'], unique=False)
        batch_op.create_index(batch_op.f('ix_ActivityLogs_Id'), ['Id'], unique=False)

    op.create_table('AgentReports',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('AgentId', sa.String(length=255), nullable=True),
    sa.Column('TenantId', sa.Integer(), nullable=True),
    sa.Column('Status', sa.String(length=50), nullable=True),
    sa.Column('CpuUsage', sa.Float(), nullable=True),
    sa.Column('MemoryUsage', sa.Float(), nullable=True),
    sa.Column('Timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    with op.batch_alter_table('AgentReports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_AgentReports_Id'), ['Id'], unique=False)

    op.create_table('Agents',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('AgentId', sa.String(length=255), nullable=True),
    sa.Column('TenantId', sa.Integer(), nullable=False),
    sa.Column('ScreenshotsEnabled', sa.Boolean(), nullable=True),
    sa.Column('LocationTrackingEnabled', sa.Boolean(), nullable=True),
    sa.Column('UsbBlockingEnabled', sa.Boolean(), nullable=True),
    sa.Column('NetworkMonitoringEnabled', sa.Boolean(), nullable=True),
    sa.Column('FileDlpEnabled', sa.Boolean(), nullable=True),
    sa.Column('LastSeen', sa.DateTime(), nullable=True),
    sa.Column('Hostname', sa.String(length=255), nullable=True),
    sa.Column('PublicIp', sa.String(length=50), nullable=True),
    sa.Column('Latitude', sa.Float(), nullable=True),
    sa.Column('Longitude', sa.Float(), nullable=True),
    sa.Column('Country', sa.Text(), nullable=True),
    sa.Column('InstalledSoftwareJson', sa.Text(), nullable=True),
    sa.Column('LocalIp', sa.String(length=50), nullable=True),
    sa.Column('Gateway', sa.String(length=50), nullable=True),
    sa.Column('PowerStatusJson', sa.Text(), nullable=True),
    sa.Column('HardwareJson', sa.Text(), nullable=True),
    sa.Column('ScreenshotQuality', sa.Integer(), nullable=True),
    sa.Column('ScreenshotResolution', sa.String(length=50), nullable=True),
    sa.Column('MaxScreenshotSize', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    with op.batch_alter_table('Agents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Agents_AgentId'), ['AgentId'], unique=True)
        batch_op.create_index(batch_op.f('ix_Agents_Id'), ['Id'], unique=False)

    op.create_table('AuditLogs',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('TenantId', sa.Integer(), nullable=True),
    sa.Column('Actor', sa.String(length=255), nullable=True),
    sa.Column('Action', sa.String(length=255), nullable=True),
    sa.Column('Target', sa.String(length=255), nullable=True),
    sa.Column('Details', sa.Text(), nullable=True),
    sa.Column('Timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    with op.batch_alter_table('AuditLogs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_AuditLogs_Id'), ['Id'], unique=False)

    op.create_table('DigitalFingerprints',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('AgentId', sa.String(length=50), nullable=True),
    sa.Column('HardwareId', sa.String(length=255), nullable=True),
    sa.Column('OS', sa.String(length=100), nullable=True),
    sa.Column('PropertiesJson', sa.Text(), nullable=True),
    sa.Column('Status', sa.String(length=50), nullable=True),
    sa.Column('FirstSeen', sa.DateTime(), nullable=True),
    sa.Column('LastSeen', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    with op.batch_alter_table('DigitalFingerprints', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_DigitalFingerprints_AgentId'), ['AgentId'], unique=False)
        batch_op.create_index(batch_op.f('ix_DigitalFingerprints_HardwareId'), ['HardwareId'], unique=False)
        batch_op.create_index(batch_op.f('ix_DigitalFingerprints_Id'), ['Id'], unique=False)

    op.create_table('EventLogs',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('AgentId', sa.String(length=50), nullable=True),
    sa.Column('Type', sa.String(length=50), nullable=True),
    sa.Column('Details', sa.Text(), nullable=True),
    sa.Column('Timestamp', sa.DateTime(), nullable=True),
    sa.Column('RawData', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    with op.batch_alter_table('EventLogs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_EventLogs_AgentId'), ['AgentId'], unique=False)
        batch_op.create_index(batch_op.f('ix_EventLogs_Id'), ['Id'], unique=False)

    op.create_table('HashBanks',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Hash', sa.String(length=255), nullable=True),
    sa.Column('Type', sa.String(length=50), nullable=True),
    sa.Column('Reputation', sa.String(length=50), nullable=True),
    sa.Column('Description', sa.String(length=255), nullable=True),
    sa.Column('Source', sa.String(length=100), nullable=True),
    sa.Column('AddedBy', sa.String(length=100), nullable=True),
    sa.Column('CreatedAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    with op.batch_alter_table('HashBanks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_HashBanks_Hash'), ['Hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_HashBanks_Id'), ['Id'], unique=False)

    op.create_table('MailLogs',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('AgentId', sa.String(length=50), nullable=True),
    sa.Column('Sender', sa.String(length=255), nullable=True),
    sa.Column('Recipient', sa.String(length=255), nullable=True),
    sa.Column('Subject', sa.String(length=255), nullable=True),
    sa.Column('BodyPreview', sa.Text(), nullable=True),
    sa.Column('HasAttachments', sa.Boolean(), nullable=True),
    sa.Column('AttachmentNames', sa.Text(), nullable=True),
    sa.Column('RiskLevel', sa.String(length=50), nullable=True),
    sa.Column('Timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    with op.batch_alter_table('MailLogs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_MailLogs_AgentId'), ['AgentId'], unique=False)
        batch_op.create_index(batch_op.f('ix_MailLogs_Id'), ['Id'], unique=False)

    op.create_table('OCRLogs',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('AgentId', sa.String(length=50), nullable=True),
    sa.Column('ScreenshotId', sa.String(length=255), nullable=True),
    sa.Column('ExtractedText', sa.Text(), nullable=True),
    sa.Column('Confidence', sa.Float(), nullable=True),
    sa.Column('SensitiveKeywordsFound', sa.Text(), nullable=True),
    sa.Column('Timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    with op.batch_alter_table('OCRLogs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_OCRLogs_AgentId'), ['AgentId'], unique=False)
        batch_op.create_index(batch_op.f('ix_OCRLogs_Id'), ['Id'], unique=False)

    op.create_table('Policies',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('TenantId', sa.Integer(), nullable=True),
    sa.Column('Name', sa.String(length=255), nullable=True),
    sa.Column('RulesJson', sa.Text(), nullable=True),
    sa.Column('Actions', sa.String(length=255), nullable=True),
    sa.Column('IsActive', sa.Boolean(), nullable=True),
    sa.Column('BlockedAppsJson', sa.Text(), nullable=True),
    sa.Column('BlockedWebsitesJson', sa.Text(), nullable=True),
    sa.Column('CreatedAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    with op.batch_alter_table('Policies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Policies_Id'), ['Id'], unique=False)

    op.create_table('SavedSearches',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=100), nullable=False),
    sa.Column('QueryJson', sa.Text(), nullable=True),
    sa.Column('Category', sa.String(length=50), nullable=True),
    sa.Column('CreatedAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    with op.batch_alter_table('SavedSearches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_SavedSearches_Id'), ['Id'], unique=False)

    op.create_table('SessionRecordings',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('AgentId', sa.String(length=50), nullable=False),
    sa.Column('Type', sa.String(length=50), nullable=True),
    sa.Column('StartTime', sa.DateTime(), nullable=True),
    sa.Column('EndTime', sa.DateTime(), nullable=True),
    sa.Column('DurationSeconds', sa.Integer(), nullable=True),
    sa.Column('VideoFilePath', sa.String(length=500), nullable=False),
    sa.Column('FileSize', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    with op.batch_alter_table('SessionRecordings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_SessionRecordings_AgentId'), ['AgentId'], unique=False)
        batch_op.create_index(batch_op.f('ix_SessionRecordings_Id'), ['Id'], unique=False)

    op.create_table('SpeechLogs',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('AgentId', sa.String(length=50), nullable=True),
    sa.Column('AudioUrl', sa.String(length=255), nullable=True),
    sa.Column('TranscribedText', sa.Text(), nullable=True),
    sa.Column('Confidence', sa.Float(), nullable=True),
    sa.Column('DurationSeconds', sa.Float(), nullable=True),
    sa.Column('FlaggedKeywordsJson', sa.Text(), nullable=True),
    sa.Column('Timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    with op.batch_alter_table('SpeechLogs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_SpeechLogs_AgentId'), ['AgentId'], unique=False)
        batch_op.create_index(batch_op.f('ix_SpeechLogs_Id'), ['Id'], unique=False)

    op.create_table('SystemSettings',
    sa.Column('Key', sa.String(length=255), nullable=False),
    sa.Column('Value', sa.Text(), nullable=True),
    sa.Column('Category', sa.String(length=50), nullable=True),
    sa.Column('Description', sa.String(length=255), nullable=True),
    sa.Column('UpdatedAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('Key')
    )
    with op.batch_alter_table('SystemSettings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_SystemSettings_Key'), ['Key'], unique=False)

    op.create_table('Tenants',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=255), nullable=True),
    sa.Column('ApiKey', sa.String(length=255), nullable=True),
    sa.Column('Plan', sa.String(length=50), nullable=True),
    sa.Column('AgentLimit', sa.Integer(), nullable=True),
    sa.Column('NextBillingDate', sa.DateTime(), nullable=True),
    sa.Column('TrustedDomainsJson', sa.Text(), nullable=True),
    sa.Column('TrustedIPsJson', sa.Text(), nullable=True),
    sa.Column('RegistrationIp', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    with op.batch_alter_table('Tenants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Tenants_Id'), ['Id'], unique=False)

    op.create_table('ThesaurusEntries',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Keyword', sa.String(length=100), nullable=False),
    sa.Column('Synonyms', sa.Text(), nullable=True),
    sa.Column('Category', sa.String(length=50), nullable=True),
    sa.Column('CreatedAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    with op.batch_alter_table('ThesaurusEntries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ThesaurusEntries_Id'), ['Id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ThesaurusEntries_Keyword'), ['Keyword'], unique=False)

    op.create_table('Users',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Username', sa.String(length=255), nullable=True),
    sa.Column('PasswordHash', sa.String(length=255), nullable=True),
    sa.Column('Role', sa.String(length=50), nullable=True),
    sa.Column('TenantId', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('Id'),
    sa.UniqueConstraint('Username')
    )
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Users_Id'), ['Id'], unique=False)

    op.create_table('Vulnerabilities',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('CVE', sa.String(length=50), nullable=False),
    sa.Column('AffectedProduct', sa.String(length=255), nullable=False),
    sa.Column('MinVersion', sa.String(length=50), nullable=True),
    sa.Column('MaxVersion', sa.String(length=50), nullable=True),
    sa.Column('Severity', sa.String(length=50), nullable=True),
    sa.Column('Description', sa.Text(), nullable=True),
    sa.Column('CreatedAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    with op.batch_alter_table('Vulnerabilities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Vulnerabilities_AffectedProduct'), ['AffectedProduct'], unique=False)
        batch_op.create_index(batch_op.f('ix_Vulnerabilities_CVE'), ['CVE'], unique=False)
        batch_op.create_index(batch_op.f('ix_Vulnerabilities_Id'), ['Id'], unique=False)

    op.create_table('MailAttachments',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('MailLogId', sa.Integer(), nullable=True),
    sa.Column('FileName', sa.String(length=255), nullable=True),
    sa.Column('ContentType', sa.String(length=100), nullable=True),
    sa.Column('Content', sa.Text(), nullable=True),
    sa.Column('Size', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['MailLogId'], ['MailLogs.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    with op.batch_alter_table('MailAttachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_MailAttachments_Id'), ['Id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('MailAttachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_MailAttachments_Id'))

    op.drop_table('MailAttachments')
    with op.batch_alter_table('Vulnerabilities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Vulnerabilities_Id'))
        batch_op.drop_index(batch_op.f('ix_Vulnerabilities_CVE'))
        batch_op.drop_index(batch_op.f('ix_Vulnerabilities_AffectedProduct'))

    op.drop_table('Vulnerabilities')
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Users_Id'))

    op.drop_table('Users')
    with op.batch_alter_table('ThesaurusEntries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ThesaurusEntries_Keyword'))
        batch_op.drop_index(batch_op.f('ix_ThesaurusEntries_Id'))

    op.drop_table('ThesaurusEntries')
    with op.batch_alter_table('Tenants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Tenants_Id'))

    op.drop_table('Tenants')
    with op.batch_alter_table('SystemSettings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_SystemSettings_Key'))

    op.drop_table('SystemSettings')
    with op.batch_alter_table('SpeechLogs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_SpeechLogs_Id'))
        batch_op.drop_index(batch_op.f('ix_SpeechLogs_AgentId'))

    op.drop_table('SpeechLogs')
    with op.batch_alter_table('SessionRecordings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_SessionRecordings_Id'))
        batch_op.drop_index(batch_op.f('ix_SessionRecordings_AgentId'))

    op.drop_table('SessionRecordings')
    with op.batch_alter_table('SavedSearches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_SavedSearches_Id'))

    op.drop_table('SavedSearches')
    with op.batch_alter_table('Policies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Policies_Id'))

    op.drop_table('Policies')
    with op.batch_alter_table('OCRLogs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_OCRLogs_Id'))
        batch_op.drop_index(batch_op.f('ix_OCRLogs_AgentId'))

    op.drop_table('OCRLogs')
    with op.batch_alter_table('MailLogs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_MailLogs_Id'))
        batch_op.drop_index(batch_op.f('ix_MailLogs_AgentId'))

    op.drop_table('MailLogs')
    with op.batch_alter_table('HashBanks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_HashBanks_Id'))
        batch_op.drop_index(batch_op.f('ix_HashBanks_Hash'))

    op.drop_table('HashBanks')
    with op.batch_alter_table('EventLogs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_EventLogs_Id'))
        batch_op.drop_index(batch_op.f('ix_EventLogs_AgentId'))

    op.drop_table('EventLogs')
    with op.batch_alter_table('DigitalFingerprints', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_DigitalFingerprints_Id'))
        batch_op.drop_index(batch_op.f('ix_DigitalFingerprints_HardwareId'))
        batch_op.drop_index(batch_op.f('ix_DigitalFingerprints_AgentId'))

    op.drop_table('DigitalFingerprints')
    with op.batch_alter_table('AuditLogs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_AuditLogs_Id'))

    op.drop_table('AuditLogs')
    with op.batch_alter_table('Agents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Agents_Id'))
        batch_op.drop_index(batch_op.f('ix_Agents_AgentId'))

    op.drop_table('Agents')
    with op.batch_alter_table('AgentReports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_AgentReports_Id'))

    op.drop_table('AgentReports')
    with op.batch_alter_table('ActivityLogs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ActivityLogs_Id'))
        batch_op.drop_index(batch_op.f('ix_ActivityLogs_AgentId'))

    op.drop_table('ActivityLogs')
    # ### end Alembic commands ###
