"""Add_MailLogs_Retry

Revision ID: a45a305a0c74
Revises: 520907ec4932
Create Date: 2026-01-02 19:01:08.293658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a45a305a0c74'
down_revision: Union[str, Sequence[str], None] = '520907ec4932'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('MailLogs',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('AgentId', sa.String(length=50), nullable=True),
    sa.Column('Sender', sa.String(length=255), nullable=True),
    sa.Column('Recipient', sa.String(length=255), nullable=True),
    sa.Column('Subject', sa.String(length=255), nullable=True),
    sa.Column('BodyPreview', sa.Text(), nullable=True),
    sa.Column('HasAttachments', sa.Boolean(), nullable=True),
    sa.Column('AttachmentNames', sa.Text(), nullable=True),
    sa.Column('RiskLevel', sa.String(length=50), nullable=True),
    sa.Column('Timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    with op.batch_alter_table('MailLogs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_MailLogs_AgentId'), ['AgentId'], unique=False)
        batch_op.create_index(batch_op.f('ix_MailLogs_Id'), ['Id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('MailLogs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_MailLogs_Id'))
        batch_op.drop_index(batch_op.f('ix_MailLogs_AgentId'))

    op.drop_table('MailLogs')
    # ### end Alembic commands ###
