"""Initial_SQLite_Schema_Fresh

Revision ID: ad63a9c9b25b
Revises: 
Create Date: 2026-01-02 16:56:28.532829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad63a9c9b25b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AgentReports',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('AgentId', sa.String(length=255), nullable=True),
    sa.Column('TenantId', sa.Integer(), nullable=True),
    sa.Column('Status', sa.String(length=50), nullable=True),
    sa.Column('CpuUsage', sa.Float(), nullable=True),
    sa.Column('MemoryUsage', sa.Float(), nullable=True),
    sa.Column('Timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    with op.batch_alter_table('AgentReports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_AgentReports_Id'), ['Id'], unique=False)

    op.create_table('Agents',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('AgentId', sa.String(length=255), nullable=True),
    sa.Column('TenantId', sa.Integer(), nullable=False),
    sa.Column('ScreenshotsEnabled', sa.Boolean(), nullable=True),
    sa.Column('LastSeen', sa.DateTime(), nullable=True),
    sa.Column('Hostname', sa.String(length=255), nullable=True),
    sa.Column('Latitude', sa.Float(), nullable=True),
    sa.Column('Longitude', sa.Float(), nullable=True),
    sa.Column('Country', sa.Text(), nullable=True),
    sa.Column('InstalledSoftwareJson', sa.Text(), nullable=True),
    sa.Column('LocalIp', sa.String(length=50), nullable=True),
    sa.Column('Gateway', sa.String(length=50), nullable=True),
    sa.Column('ScreenshotQuality', sa.Integer(), nullable=True),
    sa.Column('ScreenshotResolution', sa.String(length=50), nullable=True),
    sa.Column('MaxScreenshotSize', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    with op.batch_alter_table('Agents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Agents_AgentId'), ['AgentId'], unique=True)
        batch_op.create_index(batch_op.f('ix_Agents_Id'), ['Id'], unique=False)

    op.create_table('AuditLogs',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('TenantId', sa.Integer(), nullable=True),
    sa.Column('Actor', sa.String(length=255), nullable=True),
    sa.Column('Action', sa.String(length=255), nullable=True),
    sa.Column('Target', sa.String(length=255), nullable=True),
    sa.Column('Details', sa.Text(), nullable=True),
    sa.Column('Timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    with op.batch_alter_table('AuditLogs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_AuditLogs_Id'), ['Id'], unique=False)

    op.create_table('OCRLogs',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('AgentId', sa.String(length=50), nullable=True),
    sa.Column('ScreenshotId', sa.String(length=255), nullable=True),
    sa.Column('ExtractedText', sa.Text(), nullable=True),
    sa.Column('Confidence', sa.Float(), nullable=True),
    sa.Column('SensitiveKeywordsFound', sa.Text(), nullable=True),
    sa.Column('Timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    with op.batch_alter_table('OCRLogs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_OCRLogs_AgentId'), ['AgentId'], unique=False)
        batch_op.create_index(batch_op.f('ix_OCRLogs_Id'), ['Id'], unique=False)

    op.create_table('Policies',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('TenantId', sa.Integer(), nullable=True),
    sa.Column('Name', sa.String(length=255), nullable=True),
    sa.Column('RulesJson', sa.Text(), nullable=True),
    sa.Column('Actions', sa.String(length=255), nullable=True),
    sa.Column('IsActive', sa.Boolean(), nullable=True),
    sa.Column('BlockedAppsJson', sa.Text(), nullable=True),
    sa.Column('BlockedWebsitesJson', sa.Text(), nullable=True),
    sa.Column('CreatedAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    with op.batch_alter_table('Policies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Policies_Id'), ['Id'], unique=False)

    op.create_table('SystemSettings',
    sa.Column('Key', sa.String(length=255), nullable=False),
    sa.Column('Value', sa.Text(), nullable=True),
    sa.Column('Category', sa.String(length=50), nullable=True),
    sa.Column('Description', sa.String(length=255), nullable=True),
    sa.Column('UpdatedAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('Key')
    )
    with op.batch_alter_table('SystemSettings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_SystemSettings_Key'), ['Key'], unique=False)

    op.create_table('Tenants',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=255), nullable=True),
    sa.Column('ApiKey', sa.String(length=255), nullable=True),
    sa.Column('Plan', sa.String(length=50), nullable=True),
    sa.Column('AgentLimit', sa.Integer(), nullable=True),
    sa.Column('NextBillingDate', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    with op.batch_alter_table('Tenants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Tenants_Id'), ['Id'], unique=False)

    op.create_table('ThesaurusEntries',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Keyword', sa.String(length=100), nullable=False),
    sa.Column('Synonyms', sa.Text(), nullable=True),
    sa.Column('Category', sa.String(length=50), nullable=True),
    sa.Column('CreatedAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    with op.batch_alter_table('ThesaurusEntries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ThesaurusEntries_Id'), ['Id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ThesaurusEntries_Keyword'), ['Keyword'], unique=False)

    op.create_table('Users',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Username', sa.String(length=255), nullable=True),
    sa.Column('PasswordHash', sa.String(length=255), nullable=True),
    sa.Column('Role', sa.String(length=50), nullable=True),
    sa.Column('TenantId', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('Id'),
    sa.UniqueConstraint('Username')
    )
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Users_Id'), ['Id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Users_Id'))

    op.drop_table('Users')
    with op.batch_alter_table('ThesaurusEntries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ThesaurusEntries_Keyword'))
        batch_op.drop_index(batch_op.f('ix_ThesaurusEntries_Id'))

    op.drop_table('ThesaurusEntries')
    with op.batch_alter_table('Tenants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Tenants_Id'))

    op.drop_table('Tenants')
    with op.batch_alter_table('SystemSettings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_SystemSettings_Key'))

    op.drop_table('SystemSettings')
    with op.batch_alter_table('Policies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Policies_Id'))

    op.drop_table('Policies')
    with op.batch_alter_table('OCRLogs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_OCRLogs_Id'))
        batch_op.drop_index(batch_op.f('ix_OCRLogs_AgentId'))

    op.drop_table('OCRLogs')
    with op.batch_alter_table('AuditLogs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_AuditLogs_Id'))

    op.drop_table('AuditLogs')
    with op.batch_alter_table('Agents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Agents_Id'))
        batch_op.drop_index(batch_op.f('ix_Agents_AgentId'))

    op.drop_table('Agents')
    with op.batch_alter_table('AgentReports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_AgentReports_Id'))

    op.drop_table('AgentReports')
    # ### end Alembic commands ###
