"""Add_SystemSettings

Revision ID: cae3e22e998f
Revises: 
Create Date: 2025-12-29 21:53:23.076420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'cae3e22e998f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('SystemSettings',
    sa.Column('Key', sa.String(length=255), nullable=False),
    sa.Column('Value', sa.Text(), nullable=True),
    sa.Column('Category', sa.String(length=50), nullable=True),
    sa.Column('Description', sa.String(length=255), nullable=True),
    sa.Column('UpdatedAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('Key')
    )
    op.create_index(op.f('ix_SystemSettings_Key'), 'SystemSettings', ['Key'], unique=False)
    op.drop_table('__EFMigrationsHistory')
    op.alter_column('AgentReports', 'AgentId',
               existing_type=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_0900_ai_ci'),
               type_=sa.String(length=255),
               nullable=True)
    op.alter_column('AgentReports', 'TenantId',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('AgentReports', 'Status',
               existing_type=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_0900_ai_ci'),
               type_=sa.String(length=50),
               nullable=True)
    op.alter_column('AgentReports', 'CpuUsage',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(),
               nullable=True)
    op.alter_column('AgentReports', 'MemoryUsage',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(),
               nullable=True)
    op.alter_column('AgentReports', 'Timestamp',
               existing_type=mysql.DATETIME(fsp=6),
               nullable=True)
    op.create_index(op.f('ix_AgentReports_Id'), 'AgentReports', ['Id'], unique=False)
    op.alter_column('Agents', 'AgentId',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('Agents', 'ScreenshotsEnabled',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'1'"))
    op.alter_column('Agents', 'LastSeen',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('Agents', 'Latitude',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('Agents', 'Longitude',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.create_index(op.f('ix_Agents_AgentId'), 'Agents', ['AgentId'], unique=True)
    op.create_index(op.f('ix_Agents_Id'), 'Agents', ['Id'], unique=False)
    op.alter_column('AuditLogs', 'TenantId',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('AuditLogs', 'Actor',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('AuditLogs', 'Action',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('AuditLogs', 'Target',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('AuditLogs', 'Timestamp',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.create_index(op.f('ix_AuditLogs_Id'), 'AuditLogs', ['Id'], unique=False)
    op.alter_column('Policies', 'TenantId',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('Policies', 'Name',
               existing_type=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_0900_ai_ci'),
               type_=sa.String(length=255),
               nullable=True)
    op.alter_column('Policies', 'RulesJson',
               existing_type=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_0900_ai_ci'),
               type_=sa.Text(),
               nullable=True)
    op.alter_column('Policies', 'Actions',
               existing_type=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_0900_ai_ci'),
               type_=sa.String(length=255),
               nullable=True)
    op.alter_column('Policies', 'IsActive',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('Policies', 'CreatedAt',
               existing_type=mysql.DATETIME(fsp=6),
               nullable=True)
    op.create_index(op.f('ix_Policies_Id'), 'Policies', ['Id'], unique=False)
    op.alter_column('Tenants', 'Name',
               existing_type=mysql.LONGTEXT(),
               type_=sa.String(length=255),
               nullable=True)
    op.alter_column('Tenants', 'ApiKey',
               existing_type=mysql.LONGTEXT(),
               type_=sa.String(length=255),
               nullable=True)
    op.alter_column('Tenants', 'Plan',
               existing_type=mysql.LONGTEXT(),
               type_=sa.String(length=50),
               nullable=True)
    op.alter_column('Tenants', 'AgentLimit',
               existing_type=mysql.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'5'"))
    op.alter_column('Tenants', 'NextBillingDate',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_Tenants_Id'), 'Tenants', ['Id'], unique=False)
    op.alter_column('Users', 'Username',
               existing_type=mysql.LONGTEXT(),
               type_=sa.String(length=255),
               nullable=True)
    op.alter_column('Users', 'PasswordHash',
               existing_type=mysql.LONGTEXT(),
               type_=sa.String(length=255),
               nullable=True)
    op.alter_column('Users', 'Role',
               existing_type=mysql.LONGTEXT(),
               type_=sa.String(length=50),
               nullable=True)
    op.create_index(op.f('ix_Users_Id'), 'Users', ['Id'], unique=False)
    op.create_unique_constraint(None, 'Users', ['Username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Users', type_='unique')
    op.drop_index(op.f('ix_Users_Id'), table_name='Users')
    op.alter_column('Users', 'Role',
               existing_type=sa.String(length=50),
               type_=mysql.LONGTEXT(),
               nullable=False)
    op.alter_column('Users', 'PasswordHash',
               existing_type=sa.String(length=255),
               type_=mysql.LONGTEXT(),
               nullable=False)
    op.alter_column('Users', 'Username',
               existing_type=sa.String(length=255),
               type_=mysql.LONGTEXT(),
               nullable=False)
    op.drop_index(op.f('ix_Tenants_Id'), table_name='Tenants')
    op.alter_column('Tenants', 'NextBillingDate',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('Tenants', 'AgentLimit',
               existing_type=mysql.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'5'"))
    op.alter_column('Tenants', 'Plan',
               existing_type=sa.String(length=50),
               type_=mysql.LONGTEXT(),
               nullable=False)
    op.alter_column('Tenants', 'ApiKey',
               existing_type=sa.String(length=255),
               type_=mysql.LONGTEXT(),
               nullable=False)
    op.alter_column('Tenants', 'Name',
               existing_type=sa.String(length=255),
               type_=mysql.LONGTEXT(),
               nullable=False)
    op.drop_index(op.f('ix_Policies_Id'), table_name='Policies')
    op.alter_column('Policies', 'CreatedAt',
               existing_type=mysql.DATETIME(fsp=6),
               nullable=False)
    op.alter_column('Policies', 'IsActive',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('Policies', 'Actions',
               existing_type=sa.String(length=255),
               type_=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_0900_ai_ci'),
               nullable=False)
    op.alter_column('Policies', 'RulesJson',
               existing_type=sa.Text(),
               type_=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_0900_ai_ci'),
               nullable=False)
    op.alter_column('Policies', 'Name',
               existing_type=sa.String(length=255),
               type_=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_0900_ai_ci'),
               nullable=False)
    op.alter_column('Policies', 'TenantId',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_AuditLogs_Id'), table_name='AuditLogs')
    op.alter_column('AuditLogs', 'Timestamp',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('AuditLogs', 'Target',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('AuditLogs', 'Action',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('AuditLogs', 'Actor',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('AuditLogs', 'TenantId',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_Agents_Id'), table_name='Agents')
    op.drop_index(op.f('ix_Agents_AgentId'), table_name='Agents')
    op.alter_column('Agents', 'Longitude',
               existing_type=sa.Float(),
               type_=mysql.DOUBLE(asdecimal=True),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('Agents', 'Latitude',
               existing_type=sa.Float(),
               type_=mysql.DOUBLE(asdecimal=True),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('Agents', 'LastSeen',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('Agents', 'ScreenshotsEnabled',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('Agents', 'AgentId',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.drop_index(op.f('ix_AgentReports_Id'), table_name='AgentReports')
    op.alter_column('AgentReports', 'Timestamp',
               existing_type=mysql.DATETIME(fsp=6),
               nullable=False)
    op.alter_column('AgentReports', 'MemoryUsage',
               existing_type=sa.Float(),
               type_=mysql.DOUBLE(asdecimal=True),
               nullable=False)
    op.alter_column('AgentReports', 'CpuUsage',
               existing_type=sa.Float(),
               type_=mysql.DOUBLE(asdecimal=True),
               nullable=False)
    op.alter_column('AgentReports', 'Status',
               existing_type=sa.String(length=50),
               type_=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_0900_ai_ci'),
               nullable=False)
    op.alter_column('AgentReports', 'TenantId',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('AgentReports', 'AgentId',
               existing_type=sa.String(length=255),
               type_=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_0900_ai_ci'),
               nullable=False)
    op.create_table('__EFMigrationsHistory',
    sa.Column('MigrationId', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=150), nullable=False),
    sa.Column('ProductVersion', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=32), nullable=False),
    sa.PrimaryKeyConstraint('MigrationId'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_index(op.f('ix_SystemSettings_Key'), table_name='SystemSettings')
    op.drop_table('SystemSettings')
    # ### end Alembic commands ###
