"""Add_SavedSearches

Revision ID: d2a4c065a8e0
Revises: 6e5c925a0257
Create Date: 2026-01-02 18:29:52.612974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2a4c065a8e0'
down_revision: Union[str, Sequence[str], None] = '6e5c925a0257'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('SavedSearches',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=100), nullable=False),
    sa.Column('QueryJson', sa.Text(), nullable=True),
    sa.Column('Category', sa.String(length=50), nullable=True),
    sa.Column('CreatedAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    with op.batch_alter_table('SavedSearches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_SavedSearches_Id'), ['Id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('SavedSearches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_SavedSearches_Id'))

    op.drop_table('SavedSearches')
    # ### end Alembic commands ###
